name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
      - name: Build Web Frontend
        run: docker-compose run --rm web sh -c "npm install && npm run build"
      - name: Deploy Web Frontend
        run: |
          docker build -t your-dockerhub-username/recipe-web-frontend ./WebFrontend
          docker push your-dockerhub-username/recipe-web-frontend
